# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [9]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [10]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [13]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333+0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [12]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
# matrix_prod3 = np.dot(my_dft_matrix, my_idft_matrix)

np.set_printoptions(suppress=True)
# print(matrix_prod1)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

## Answer

1.Yes,circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse. Since for all A=circulant([a, b, c]) matrices, $F\cdot A\cdot F^{-1}$=$
\left[
\begin{matrix}
f(a,b,c) ; 0         ; 0  \\
0        ; g(a,b,c)  ; 0 \\
0        ; 0         ; h(a,b,c)\\ 
\end{matrix}
\right] $


2.Yes, product of circulant matrices (of a same size) always circulant matrices. Since the circulant matrix follows the algebraic algorithm. For both circulant matrices A and B(the same size), A + B is also a circulant matrix. AB is also a circular matrix, and AB = BA.

3.Yes, all pairs of circulant matrices commute under matrix multiplication for them follow the algebraic algorithm. Take A=circulant([a, b, c]) and B=circulant([a', b', c']) as an example. AB=BA=$
\left[
\begin{matrix}
aa' + bc' + cb' ; ac' + bb' + ca' ; ab' + ba' + cc' \\
ab' + ba' + cc' ; aa' + bc' + cb' ; ac' + bb' + ca' \\
ac' + bb' + cb' ; ab' + ba' + cc' ; aa' + bc' + cb'
\end{matrix} 
\right] $ ,

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [14]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [22]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)
# print(A_step1)

17.97936


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

#### Answer

1.

In the example, my_circ_matrix = circulant([1, 2, 3]),so my_circ_matrix=$
\left[
\begin{matrix}
1 ,3 ,2\\
2 ,1 ,3\\
3 ,2 ,1
\end{matrix}
\right]
$
and det(my_circ_matrix)=$1^3+2^3+3^3-3*1*2*3=18.0$ 

Since np.identity(len(A_step1))=np.indentity(3)=$
\left[
\begin{matrix}
1 ,0 ,0\\
0 ,1 ,0\\
0 ,0 ,1
\end{matrix}
\right]
$
permutation_matrix has six different types, and the probability of each occurrence is almost the same(because max_index is big enough). Thus, the probability of sign_permutation to be +1 or -1 is the same too. Meanwhile, A_step1=$
\left[
\begin{matrix}
0           ,   1.09861229  ,   0.69314718\\
0.69314718  ,   0           ,   1.09861229\\
1.09861229  ,   0.69314718  ,   0        
\end{matrix}
\right]
$

that's to say np.trace(np.dot(A_step1, permutation_matrix)) can only be four values: 1.79175946923,   0.0,  3.295836866,  2.07944154168.
Amoung these values, 1.79175946923 has 1/2 probability to occurrence, other three has 1/6 probability to occurrence. Those four values show that np.exp(np.trace(np.dot(A_step1, permutation_matrix)))= -6 ,1 ,27 ,8 respectively.We can assume max_index=6 and the probability is 3:1:1:1. Thus, a_step2 = math.factorial(len(A_step1)) * current_value / max_index= 3!*current_value/max_index = 3!*18/6=18.0.

This result equals to det(my_circ_matrix). Because of the probability to occurrence will not be so rigorous, the two results will be closed.

2.

This finding can be extended to arbitrary matrices over the real numbers! Since the result is decided by the probability of occurence, if the probability of sign_permutation and np.trace(np.dot(A_step1, permutation_matrix)) values to be the same, then the results would be closed! 

In another words, if the max_index is big enough, then the two results would be closed!

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [70]:
import numpy as np
from scipy.linalg import det

n=np.random.randint(2,10)
print("n is",n)

A=np.zeros((n,n))
B=np.zeros((n,n))

for i in range(0,n,1):
    for j in range(0,n,1):
     A[i][j]=np.random.randint(1,10)
for i in range(0,n,1):
    for j in range(0,n,1):
     B[i][j]=np.random.randint(1,10)
    
AB=np.dot(A,B)
det1=det(B)*det(A)
det2=det(AB)

print("A is",'\n',A)
print("B is",'\n',B)
print("AB is",'\n',AB)
print("det(A)*det(B) is",det1)
print("det(AB) is",det2)


n is 7
A is 
 [[ 7.  3.  5.  6.  2.  9.  9.]
 [ 5.  7.  7.  5.  8.  7.  1.]
 [ 8.  3.  1.  6.  1.  5.  5.]
 [ 5.  4.  1.  2.  6.  5.  1.]
 [ 2.  7.  3.  4.  6.  8.  1.]
 [ 7.  5.  2.  9.  5.  2.  8.]
 [ 4.  1.  9.  8.  8.  5.  9.]]
B is 
 [[ 7.  4.  7.  7.  7.  8.  1.]
 [ 1.  9.  7.  5.  4.  5.  9.]
 [ 2.  7.  6.  7.  1.  2.  9.]
 [ 1.  2.  4.  3.  9.  1.  8.]
 [ 5.  2.  5.  3.  7.  6.  4.]
 [ 9.  7.  6.  9.  8.  3.  1.]
 [ 7.  7.  1.  1.  6.  5.  3.]]
AB is 
 [[ 222.  232.  197.  213.  260.  171.  171.]
 [ 171.  214.  229.  222.  233.  168.  213.]
 [ 152.  150.  147.  149.  200.  133.  116.]
 [ 125.  121.  138.  132.  158.  120.   98.]
 [ 140.  175.  176.  173.  193.  126.  159.]
 [ 166.  185.  177.  156.  251.  170.  188.]
 [ 203.  218.  200.  198.  263.  171.  222.]]
det(A)*det(B) is -47836100000.000015
det(AB) is -47836099999.999985


As shown in the result, the determinant function is multiplicative.