# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [2]:
from scipy.linalg import circulant
my_circ_matrix = circulant([ 1, 2, 3])
print (my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [3]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print (my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [4]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print (my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [5]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod1)
print('\n')
print(matrix_prod2)

[[ 6.0+0.j          6.0+0.j          6.0+0.j        ]
 [-1.5+0.8660254j   1.5+0.8660254j   0.0-1.73205081j]
 [-1.5-0.8660254j   1.5-0.8660254j  -0.0+1.73205081j]]


[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers

 * Circulant matrices are always diagonalized by the discrete Fourier transform matrix and its inverse.  
 We want to prove $ P \cdot C \cdot P^{-1} $ equal to a diagonal matrix , $ P$ is DFT matrix.  
 That is to prove each column vector of $ P$ is a eigenvector of a circulant matrix $ C$.  
 Let $ C$ be a circulant matrix and the columns of $ C$ denoted by $ \underline{c_1,...c_n}$, if $ p =(p_1,p_2,...p_n)$is a column vector of $ P$.  
 because $ C$ is a circulant matrix, is easy to find that the sum of each column is a constant $ k$, which means $$ C \cdot p = \Sigma_{i=1}^n \cdot p_i \cdot \underline{c_i} = k \cdot p$$
 which is the definiton of eigenvector, $ k$ is a eigenvalue.
 Hence, $ P \cdot C \cdot P^{-1} $ equal to a diagonal matrix.
 
 * Product of circulant matrices(of a same size) are always a circulant matrices. According to answer1:    
 if  $ C = U \cdot \Psi \cdot U^{-1} and D = U \cdot \Phi \cdot U^{-1} $  $\Psi$ and $\Phi$ are diagonal matrix, (U = P^{-1})  
 then    
    >$ CD = (U \cdot \Psi \cdot U^{-1}) \cdot (U \cdot \Phi \cdot U^{-1}) $   
    $ = U \cdot \Psi \cdot (U^{-1} \cdot U) \cdot \Phi \cdot U^{-1} $  
    $ = U \cdot (\Psi \cdot \Phi ) \cdot U^{-1} $.  
 
 * All pairs of circulant matrices commute under matrix multiplication. According to answer2:  
 if  $ C = U \cdot \Psi \cdot U^{-1} and D = U \cdot \Phi \cdot U^{-1} $  $\Psi$ and $\Phi$ are diagonal matrix, then    
    $ CD = U \cdot (\Psi \cdot \Phi ) \cdot U^{-1} $  
    $ DC = U \cdot (\Phi \cdot \Psi ) \cdot U^{-1} $    
 because $\Psi$ and $\Phi$ are diagonal matrix, which can easily prove that $ \Psi \cdot \Phi = \Phi \cdot \Psi $   
 Hence, $　CD = DC $.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [6]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [35]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0

for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permutation = det(permutation_matrix)
    current_value += sign_permutation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)
print(det(my_circ_matrix))

17.85474
18.0


### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

### Answers

 * the current_value = 
 $ \sum_{i=1}^{max} \mathrm{det}(P_i) \cdot e^{tr(ln(C) \cdot P_i))}$   
 the a_step2 = 
 $ \frac{n!}{max}\cdot$ current_value   
If the number of the loop max is large enough, the permutation metrics made by random function will appear in equal probabilities, and the value of a_step2 will equal to the value of det(my_circ_matrix).
 
 * Yes, this property can extend to arbitrary matrices over real numbers.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [30]:
from numpy import random
from scipy.linalg import det
import numpy as np

n = random.randint(2,6)

print('let A be a', n,'x', n, 'metrix:')
A = random.randint(1, 10, size=(n, n))   
print(A, '\n')

print('let B be a', n,'x', n, 'metrix:')
B = random.randint(1, 10, size=(n, n))
print(B, '\n')

AB = np.dot(A,B)                       
print('matrix AB is:')
print(AB, '\n')

Det_A = det(A)
Det_B = det(B)
Det_AB = det(AB)

print('det(A) =',Det_A)
print('det(B) =',Det_B)
print('det(AB) =',Det_AB)
print('det(A) * det(B) =',Det_A*Det_B, '\n')

if (abs(Det_AB - Det_A*Det_B)<0.00001):
    print('det(AB) = det(A)*det(B)')
    print('Hence, determinant Function is Multiplicative.')

let A be a 5 x 5 metrix:
[[5 6 8 5 4]
 [3 5 4 8 9]
 [4 8 7 4 1]
 [9 1 2 4 9]
 [6 9 1 9 4]] 

let B be a 5 x 5 metrix:
[[5 4 3 9 2]
 [3 3 7 1 2]
 [8 7 3 6 9]
 [6 6 6 9 9]
 [7 9 2 8 7]] 

matrix AB is:
[[165 160 119 176 167]
 [173 184 122 200 187]
 [131 122 115 130 130]
 [151 158  82 202 137]
 [147 148 146 182 148]] 

det(A) = 5556.000000000002
det(B) = 5000.999999999996
det(AB) = 27785555.999999873
det(A) * det(B) = 27785555.99999999 

det(AB) = det(A)*det(B)
Hence, determinant Function is Multiplicative.
