# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [85]:
import random
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])

Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [86]:
from scipy.linalg import dft
my_dft_matrix = dft(3)

The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [87]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)

The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [88]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

1.Yes , Circulant matrices are always diagonised by the discrete Fourier transform matrix and its inverse. 

2.Yes, The product of same size circulant matrices are always circulant

3.All pairs of circular matrices commute under the matrix multiplication

I have written a code that generates a random circulant matrix and used that matrix to prove the above qns.

In [89]:
cir_matrix = circulant([random.randint(1,10),random.randint(1,10),random.randint(1,10)])
matrix_prod1 = np.dot(my_dft_matrix, cir_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
print(matrix_prod2)

[[ 9.-0.j  0.+0.j  0.+0.j]
 [-0.-0.j  3.+0.j  0.+0.j]
 [ 0.-0.j -0.+0.j  3.+0.j]]


In [90]:
product= np.dot(cir_matrix,my_circ_matrix)
print(product)

[[15 21 18]
 [18 15 21]
 [21 18 15]]


In [91]:
product1 = np.dot(cir_matrix,my_circ_matrix)
product2 = np.dot(my_circ_matrix,cir_matrix)

if(product1.all()==product2.all()):
    print("Commutative property holds for multiplication of circulant matrices")
else:
    print("Does not Commute under matrix multiplication")

Commutative property holds for multiplication of circulant matrices


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [92]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [93]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)


max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

17.85054


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 
 The determinant of a matrix can be expressed as sum of products with co-efficients being -1 or 1 or 0. The expression growing with the size of the matrix n ( n! terms for an nxn matrix ). sign_permutation gives the co-efficient of each term and iteration calculates the summation of average values of the n! terms. This value a_step2  gives a value which is close to the determinant. It is not equal to the determinant value since the permutation matrix provides only a subset of possible solutions. 
 
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?
 Yes, This property can be extended to arbitrary matrices over the real numbers.
 

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [94]:
matrix1= ([random.randint(1,10),random.randint(1,10),random.randint(1,10)],[random.randint(1,10),random.randint(1,10),random.randint(1,10)],[random.randint(1,10),random.randint(1,10),random.randint(1,10)])
matrix2= ([random.randint(1,10),random.randint(1,10),random.randint(1,10)],[random.randint(1,10),random.randint(1,10),random.randint(1,10)],[random.randint(1,10),random.randint(1,10),random.randint(1,10)])

detMat1= round(det(matrix1),3)
detMat2= round(det(matrix2),3)

detmat= round(det(np.dot(matrix1,matrix2)),3)
proddet= round(detMat1*detMat2,3)

print('Det mat A=',detMat1)
print('Det mat B=',detMat2)
print('Det mat AB=',detmat)
print('Det mat A * Det mat B=',proddet)
if(detmat==proddet):
    print("It is proved that det(AB)=det(A)*det(B)")
else:
    print("They are not equal")



Det mat A= 260.0
Det mat B= -598.0
Det mat AB= -155480.0
Det mat A * Det mat B= -155480.0
It is proved that det(AB)=det(A)*det(B)
