# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [22]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(" Circulant Matrix is \n")
print(my_circ_matrix)

 Circulant Matrix is 

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [23]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(" Discrete Fourier Transform Matrix is \n")
print(my_dft_matrix)

 Discrete Fourier Transform Matrix is 

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [24]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print("Inverse of DFT matrix is \n")
print(my_idft_matrix)

Inverse of DFT matrix is 

[[ 0.33333333+0.j          0.33333333+0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [25]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j         0.0+0.j        -0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

1. Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
Sol:- Yes, Circulant matrices are always diagnolized by the DFT matrix and it's Inverse matrix.
if C is circulant matrix, then C = F^-1.Δ.F,  where Δ is a Diagnol Matrix.
    F.C = F.F^-1.Δ.F = Δ.F 
 => F.C.F^-1 = Δ.F.F^-1 
 => Δ a Diagnol Matrix. and C = circulant([a,b,c])
 
 Δ = F.C.F^-1 = 
 [[ f(a,b,c)   0       0    ]
  [ 0       g(a,b,c)   0    ]
  [ 0          0    h(a,b,c)] ]
  
2. Are product of circulant matrices (of a same size) always circulant matrices?
Sol:- Yes, product of Circulant matrices(of a same size) is always a Circulant matrix.
The sum or product of two circulant matrices is also circulant:
if C = U.Ψ.U^-1 and  D = U.ϕ.U^-1, then C+D = U.(Ψ+ϕ).U^-1 and CD = DC = U.(Ψϕ).U^-1 .

3. Do all pairs of circulant matrices commute under matrix multiplication?
Sol:- Yes, all pairs of Circulant Matrices commute under matrix multiplication and it is same as the matrix multiplication. If A = circulant([a,b,c]) and B = circulant([a',b',c'])
AB = 
 [[ aa'+bc'+cb'  ac'+bb'+ca'  ab'+ba'+cc']
  [ ab'+ba'+cc'  aa'+bc'+cb'  ac'+bb'+ca']
  [ ac'+bb'+cb'  ab'+ba'+cc'  aa'+bc'+cb']  = BA.
 

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [30]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [34]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)
print(A_step1)
max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print("\na_step2 is ",a_step2)

[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]

a_step2 is  18.4425


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

1. Go through the code and provide a compelling explain explanation of why these numbers are close?
Sol:- There are two numbers, the former number is direct calculation of determinant of the matrix.
    If A = [[a c b];[b a c];[c b a]] then det(my_circ_matrix) = a(a.a-b.c)-c(a.b-c.c)+b(b.b-a.c)
    => a^3+b^3+c^3 - 3.a.b.c = applying this gave the value of 18.
    
    The later number is caclulated by the formula 
a_step2 = (sum{det(permutation_matrix)*exp(trace(ln(my_circ_matrix))*[permutation_matrix])}) *3!)/max_index
where permutation_matrix is randomly generated and it has 6 different permutations as below:
[[1 0 0];[0 1 0];[0 0 1]]  [[1 0 0];[0 0 1];[0 1 0]]  [[0 1 0];[0 0 1];[1 0 0]] 
[[0 1 0];[1 0 0];[0 0 1]]  [[0 0 1];[0 1 0];[1 0 0]]  [[0 0 1];[1 0 0];[0 1 0]]

In the above code, random function inside for loop, makees the permutations have equal probabilities as the max_index is large enough i.e 10000. if the max_index is simplified to 6 probability will be 3:1:1:1, then we will have each permutation of "P" occurs as previous. This results in the formula to get the value of a_step2 = a^3+b^3+c^3 - 3.a.b.c, which is equal to the determinant value of the circular matrix, and a_step2 = 3!*18/6 = 18.0

But, probability of the 6 permutations is not exactly the same in this case, but approximately equal, hence the numbers are very close enough. 


2. Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

Sol:- yes, This finding can be extended to arbitrary matrices over the real numbers. As the result is caclulated based on the probability of the occurence of the permutations mentioneed above and np.trace(np.dot(A_step1, permutation_matrix)) values to be the same, then the results would be closed. 



### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [40]:
#import statements like numpy and scipy
import numpy as np
from scipy.linalg import det

#random number to generate the dimension of the matrix.
dimnsn = np.random.randint(3,10)
print("dimension of the matrix is ",dimnsn,"X",dimnsn)

#initialize the two matrices
A = np.zeros((dimnsn,dimnsn))
B = np.zeros((dimnsn,dimnsn))

#Generation of the two matrices randomly
for a in range(0,dimnsn,1):
    for b in range(0,dimnsn,1):
        A[a][b] = np.random.randint(0,dimnsn)
print("Matrix A is :\n",A)
for c in range(0,dimnsn,1):
    for d in range(0,dimnsn,1):
        B[c][d] = np.random.randint(0,dimnsn)
print("\nMatrix B is :\n",B)
#Left Hand Side definition
AXB = np.dot(A,B)
print("\ndot prodduct of AB is :\n",AXB)
det_AB = det(AXB)

#Right hand sie definition 
det_AXdet_B = det(A)*det(B)

print("\n det(A.B) is :",det_AB)
print("\n det(A)*det(B) is: ",det_AXdet_B)

# to check if det(AB) = det(A)*det(B).
if (abs(det_AB-det_AXdet_B)<0.00001):
    print("\n det(AB) = det(A)*det(B)\n")
    print("Determinant Function is Multiplicative")
else:
    print("Determinant Function is not Multiplicative")


dimension of the matrix is  6 X 6
Matrix A is :
 [[ 0.  4.  4.  5.  5.  5.]
 [ 4.  2.  3.  4.  4.  3.]
 [ 4.  3.  1.  4.  0.  0.]
 [ 1.  4.  3.  3.  3.  1.]
 [ 5.  0.  0.  3.  0.  5.]
 [ 1.  5.  0.  4.  2.  2.]]

Matrix B is :
 [[ 0.  4.  3.  2.  0.  4.]
 [ 2.  3.  1.  4.  2.  4.]
 [ 1.  2.  2.  0.  1.  5.]
 [ 1.  0.  4.  2.  0.  1.]
 [ 5.  2.  4.  0.  2.  2.]
 [ 1.  2.  3.  5.  0.  1.]]

dot prodduct of AB is :
 [[ 47.  40.  67.  51.  22.  56.]
 [ 34.  42.  61.  39.  15.  54.]
 [ 11.  27.  33.  28.   7.  37.]
 [ 30.  30.  40.  29.  17.  45.]
 [  8.  30.  42.  41.   0.  28.]
 [ 26.  27.  38.  40.  14.  34.]]

 det(A.B) is : 719120.0000000023

 det(A)*det(B) is:  719119.9999999997

 det(AB) = det(A)*det(B)

Determinant Function is Multiplicative
