# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [2]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### solution
1. Yes. We have $X=F*diag(x)*F^H$. It is the property of circulant matrices.
2. Yes.
  We assume there are two circulant matrices $A$ and $B$. $A$ = [$A_1,A_2,...,A_n$], $B = [B_1,B_2,...,B_n]^T$ and $C = A*B = [AB_1,AB_2,...,AB_n] = [ΣA_iB_1,……,ΣA_iB_n]$ where i = n. Due to distributive law of multiplication, $ΣA_iB_j=(ΣA_i) * B_j$. Let $A_0 = ΣA_i$, we can know that A_0 is a vector of the sum of every element in colunm by the property of circulant matrix. Let every element in A_0 equals to K, then $C=[A_0B_1,……,A_0B_n]=[kB_0,...,kB_n]=kB$. Since $B$ is a circulant matrice, KB is a circulant matrice. Therefore, the product of circulant matrices (of a same size) are always circulant matrices.
3. Yes.
  We assume there are two circulant matrices $A$ and $B$ where A = a0I + a1D + a2D^2 + a(n-1)D^(n-1) = f(D),  B = b0I + b1D + b2D^2 + b(n-1)D^(n-1) = g(D). D is the basic circulant matrix of order n, $D = circ(0,1,0,...,0)$. Since D^n = D^(n+k) where k is nonnegetive integer and $D^0=I$, $AB=f(D)g(D)=g(D)f(D)=BA$. Therefore, all pairs of circulant matrices commute under matrix multiplication.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [4]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [7]:
import math
from numpy import random
import numpy as np

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.00108


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

### Solution
1. By the property of circulant matrix, for a 3x3 matrix, suppose a $A=[a,b,c;c,a,b;b,c,a]$,then $det(A)=a^3+b^3+c^3-3abc$.
The code is performing the following $$\mathbf{logA} = \left[\begin{array}
{rrr}
\log(1) ; log(3) ; log(2) \\
log(2) ; log(1) ; log(3) \\
log(3) ; log(2) ; log(1)
\end{array}\right]
$$
This step wants to change the matrix multiplication into addition.
Next, we shuffle the Identity matrix which has the same dimension with the original matrix and use the matrix that we get above to dot with the shuffled Identity matrix, This step help us prepare to let this method has the same function as determination.
Then we do trace and exp to the matrix. This step wants to get elements which are equal to the dimension of the orginal matrix and each of them has to be distinct, so it can has the same function as we do determine, and also turn it property form addition back to mutiplication by doing exp to the elements. Permutation_matrix is randomly generated and it has 6 different permutations as below: [1,0,0;0,1,0;0,0,1], [1,0,0;0,0,1;0,1,0], [0,1,0;1,0,0;0,0,1], [0,1,0;0,0,1;1,0,0], [0,0,1;1,0,0;0,1,0], [0,0,1;0,1,0;1,0,0].
If the time of producing permutation_matrix of six forms are same, a_step2=a^3+b^3+c^3-3abc, which equals to det(my_cric_matrix). In fact, the times may not same but they are very close if the loop have enough times(eg. index=100000). So a_step2 is close to det(my_cric_matrix).

2.It can be extend to arbitrary matrices over the real numbers.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [9]:
import math
from scipy.linalg import det
from numpy import random
import numpy as np

n = random.randint(2,8)
my_matrixA = np.random.randint(1,10,(n,n))
print("Matrix A is as follows:")
print(my_matrixA, '\n')
my_matrixB = np.random.randint(1,10,(n,n))
print("Matrix B is as follows:")
print(my_matrixB, '\n')

matrix_prodAB = np.dot(my_matrixA, my_matrixB)
detA = det(my_matrixA)
detB = det(my_matrixB)
detAB = round(detA*detB)
det_prodAB =round(det(matrix_prodAB))

print('det(A) =',detA)
print('det(B) =',detB)
print('det(AB) =',detAB)
print('det(A) * det(B) =',det_prodAB, '\n')


if(det_prodAB==detAB):
    print("determinant function is multiplicative:  det(AB)= det(A)det(B) = "+str(det_prodAB))
else:
    print("determinant function is NOT multiplicative:  det(AB) = "+str(det_prodAB)+", det(A)*det(B) = "+str(detAB))

Matrix A is as follows:
[[8 1 3]
 [3 1 3]
 [8 8 1]] 

Matrix B is as follows:
[[8 3 1]
 [7 9 4]
 [2 4 1]] 

det(A) = -115.0
det(B) = -42.99999999999999
det(AB) = 4945
det(A) * det(B) = 4945 

determinant function is multiplicative:  det(AB)= det(A)det(B) = 4945
