# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [3]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [4]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [5]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [6]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


In [7]:
test_circulant = circulant([2,4,5])
print(test_circulant)

[[2 5 4]
 [4 2 5]
 [5 4 2]]


In [8]:
result_matrix = my_dft_matrix@test_circulant@my_idft_matrix
print(result_matrix)

[[ 11.0+0.j         -0.0+0.j          0.0+0.j       ]
 [ -0.0-0.j         -2.5+0.8660254j  -0.0-0.j       ]
 [  0.0-0.j          0.0-0.j         -2.5-0.8660254j]]


In [9]:
test_circulant_2=circulant([3,4,7])
print(test_circulant_2)
result_circulant_product = test_circulant@test_circulant_2

[[3 7 4]
 [4 3 7]
 [7 4 3]]


In [10]:
commute_product = test_circulant_2@test_circulant
print(commute_product)
print(result_circulant_product)

[[54 45 55]
 [55 54 45]
 [45 55 54]]
[[54 45 55]
 [55 54 45]
 [45 55 54]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

Answers:
1. Circulant matrices are always diagnalized by the Fourier transform matrix and its inverse. This is demonstrated by the code in Input 12. The answer came from research on the internet. https://en.wikipedia.org/wiki/Circulant_matrix
2. Circulant matrices are always circulant matrices. This is demonstrated in Input 17 and was confirmed by research on the internet. https://en.wikipedia.org/wiki/Circulant_matrix
3. Also, all pairs of circulant matrices commute under matrix multipliction. This is demonstrated by Input 17 and was confirmed by research on the internet. https://en.wikipedia.org/wiki/Circulant_matrix

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [11]:
from scipy.linalg import det
det(my_circ_matrix)
print(my_circ_matrix)
print(det(my_circ_matrix))

[[1 3 2]
 [2 1 3]
 [3 2 1]]
18.0


The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [12]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.12486


In [16]:
print(len(A_step1))
print(A_step1)
print(my_identity)
print(permutation_matrix)
print(current_value)
print(math.factorial(len(A_step1)))

3
[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
302081.0
6


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

Answers:
    1. The code uses random permutations of the identity matrix and logarithms to attempt to approximate calculating the actual determinant. The logarithms allow one to use addition instead of multiplication to approximate the determinant. Using the dot function and the exp function essentially calculates the sum of the components of the matrix and then undoes the logarithm. After some research, it was discovered that the "determinant of a matrix is the sum over all possible ways of selecting entries." https://www.math.ucdavis.edu/~anne/WQ2007/mat67-Lm-Determinant.pdf. Thus, the code is taking advantage of this definition of the determinant.  
    2. This property should be extensible to arbitrary matrices over the real numbers. There was nothing actaully in the code that required a circular matrix, and no particular property was taken advantage of pertaining to a circular matrix.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [14]:
test_matrix_1 = circulant([1,2,3])
test_matrix_2 = circulant([4,5,6])
det_of_products = det(test_matrix_1@test_matrix_2)
product_of_dets = det(test_matrix_1)*det(test_matrix_2)

In [15]:
print(det_of_products)
print(product_of_dets)

810.0000000000002
810.0


They appear to be very similar. I believe the extraneous decimal of the det_of_products is insignificant, and they are equal.