# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])

Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [2]:
from scipy.linalg import dft
my_dft_matrix = dft(3)

The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)

The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers
* Yes, a property of circulant matrices is that it is diagonalized by the discrete fourier transform matrix and its inverse.
* Yes, the product of circulant matrices of a same size are always circulant matrices.
* All pairs of circulant matrices commute under matrix multiplication. 

In [6]:
#Example shows product of circulant matrices of a same size are always circulant matrices
import numpy as np
from scipy.linalg import circulant
from scipy.linalg import dft
from scipy.linalg import inv

circ_matrix1 = circulant([4, 2, 3])
circ_matrix2 = circulant([7, 5, 4])

matrix_prod1 = np.dot(circ_matrix1, circ_matrix2)

np.set_printoptions(suppress=True)
print(matrix_prod1)

[[51 47 46]
 [46 51 47]
 [47 46 51]]


In [7]:
#Example showing commutability under matrix multiplication
import numpy as np
from scipy.linalg import circulant
from scipy.linalg import dft
from scipy.linalg import inv

circ_matrix1 = circulant([4, 2, 3])
circ_matrix2 = circulant([7, 5, 4])

matrix_prod1 = np.dot(circ_matrix1, circ_matrix2)
matrix_prod2 = np.dot(circ_matrix2, circ_matrix1)

np.set_printoptions(suppress=True)
print(matrix_prod1)
print(matrix_prod2)

[[51 47 46]
 [46 51 47]
 [47 46 51]]
[[51 47 46]
 [46 51 47]
 [47 46 51]]


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [ ]:
from scipy.linalg import det
det(my_circ_matrix)

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [ ]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

### Answers
* The current value variable is a sum such that it is equal to the sum of det(permutation_matrix)e^(trace(ln(circular_matrix) * permutation_matrix)). After summing this result over many permutations, a_step2 approaches the value of det(my_circ_matrix). a_step2 = n!/maxindex. As the number of loops increases, the output of the loop will be close to the determinate of the circular matrix.

* This property would extend to arbitrary matrices over the real numbers.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [20]:
from numpy import random
from scipy.linalg import det
import numpy as np

A = np.random.randint(1,9,(5,5))
B = np.random.randint(1,9,(5,5))
AB = np.dot(A,B)
DetA = det(A)
DetB = det(B)
DetAB = det(AB)

print('det(AB) =',DetAB)
print('det(A) * det(B) =',DetA*DetB, '\n')

if (round(DetAB) == round(DetA*DetB)):
    print('det(AB) = det(A)*det(B) \nThe determinant Function is multiplicative.')

det(AB) = -9518949.000000013
det(A) * det(B) = -9518948.999999998 

det(AB) = det(A)*det(B) 
The determinant Function is multiplicative.
