# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [4]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])

Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [5]:
from scipy.linalg import dft
my_dft_matrix = dft(3)

The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [6]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)

The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [7]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 . Yes circulant matrices are always diagonalized by the DFT matrix and its inverse. Any circulant matrix can be denoted by 
   C = UDU* where U -> Unitary DFT matrix, U* -> conjugate transpose of the Unitary DFT matrix and D is a diagonal matrix.
 * Are product of circulant matrices (of a same size) always circulant matrices?
 . Yes products of circulant matrices of same size are always circulant matrices.
 * Do all pairs of circulant matrices commute under matrix multiplication?
 . As circulant matrices are diaganolizable, their matrix multiplication is commutative.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [9]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permutation = det(permutation_matrix)
    current_value += sign_permutation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.0201


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 . The code effectively calculates the determinant of "my_circ_matrix". The key here is the number of iterations. Since there is    equal probability of drawing any permutation matrix, the more times the random() is called there is higher chance of the dot    (A_step1, permutation) function capturing the essential elements for finding the determinant. Since the determinant of        any NxN matrix has N! terms for summation, the a_step2 variable is calculated by capturing the average of N! most probable      determinant terms. Hence, more the number of iterations, closer is the estimation.
 
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?
 . This property can be extended to arbitrary matrices over the real numbers.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [10]:
import numpy as np
import math
from numpy import random
from scipy.linalg import det
A = random.randint(1, 100, (3,3))
print "A is: ", A
B = random.randint(10, 1000, (3,3))
print "B is: ", B
DetA = det(A)
print "Det A is: ", DetA
DetB = det(B)
print "Det B is: ", DetB
DetAB = det(np.dot(A,B))
print "Det(AB) is: ", DetAB
DetAxDetB = DetA*DetB
print "Det(A)*Det(B) is: ", DetAxDetB
if round(DetAB) == round(DetAxDetB):
    print "det(AB) = det(A)det(B)"
    
    
    



A is:  [[29 48 56]
 [15 96 87]
 [48 43 22]]
B is:  [[459 737 834]
 [675 855 233]
 [972 362 685]]
Det A is:  -84561.0
Det B is:  -433063692.0
Det(AB) is:  3.66202988592e+13
Det(A)*Det(B) is:  3.66202988592e+13
det(AB) = det(A)det(B)
