# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [119]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
#Each row vector is rotated one element to the right relative to the preceding row vector.
#Single row/column completely determines the entire matrix.
print("My circulant matrix")
print(my_circ_matrix)

# Product of circulant matrices (of a same size) is always circulant matrices
my_circ_matrix1 = circulant([9,8,5])
print("\n Product of circulant matrices (of a same size) is always circulant matrices")
print(np.dot(my_circ_matrix,my_circ_matrix1))
print("\n All pairs of circulant matrices commute under matrix multiplication")
print(np.dot(my_circ_matrix1,my_circ_matrix))


My circulant matrix
[[1 3 2]
 [2 1 3]
 [3 2 1]]

 Product of circulant matrices (of a same size) is always circulant matrices
[[43 48 41]
 [41 43 48]
 [48 41 43]]

 All pairs of circulant matrices commute under matrix multiplication
[[43 48 41]
 [41 43 48]
 [48 41 43]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [118]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print("Discrete Fourier transform matrix ")
print(my_dft_matrix)

Discrete Fourier transform matrix 
[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [117]:
from scipy.linalg import inv
#Compute the inverse of a matrix.
my_idft_matrix = inv(my_dft_matrix)
print("Inverse of a matrix")
print(my_idft_matrix)

Inverse of a matrix
[[ 0.33333333+0.j          0.33333333+0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [115]:
import numpy as np
# np.dot(a,b) - Returns the dot product of a and b. Array is returned. 
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
print("\n DFT matrix \n",matrix_prod1)
#suppress : bool, optional
#Whether or not suppress printing of small floating point values using scientific notation (default False).
np.set_printoptions(suppress=True) 
print("\n IDFT matrix \n",matrix_prod2)


 DFT matrix 
 [[ 6.0+0.j          6.0+0.j          6.0+0.j        ]
 [-1.5+0.8660254j   1.5+0.8660254j   0.0-1.73205081j]
 [-1.5-0.8660254j   1.5-0.8660254j  -0.0+1.73205081j]]

 IDFT matrix 
 [[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers

 * Circulant matrices (C) are always diagonalized by a discrete Fourier transform (F) and its inverse F^{-1}
 * Given circulant matrices A and B (of same size), the product AB is always circulant.
 * A set of matrices is said to commute if they commute pairwise,every pair of matrices in the set commute with each other. Under matrix multiplication, all pairs of circulant matrices commute with each other. 
      Given circulant matrices A and B, AB=BA
        

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [64]:
from scipy.linalg import det
det(my_circ_matrix)
print(det(my_circ_matrix))

18.0


The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [114]:
%%time
import time
import math
from numpy import random

def my_log(x):
    return math.log(x)

#Define a vectorized function which takes a nested sequence of objects or numpy arrays as inputs and returns a numpy array as output. 
#The vectorized function evaluates pyfunc over successive tuples of the input arrays like the python map function.
my_vec_log = np.vectorize(my_log)
A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
my_identity = np.identity(len(A_step1)) # Identity matrix (of same size as Circulant matrix)  

#initialize 
current_value = 0.0
max_index = 10000
#for loop
for my_index in range(0, max_index):
    #A permutation matrix is a square binary matrix that has exactly one entry of 1 in each row and each column and 0s elsewhere.
    permutation_matrix = random.permutation(my_identity) #Random permutation of identity matrix
    sign_permutation = det(permutation_matrix) # Determinant of Random permutation of identity matrix
    current_value += sign_permutation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix)))) # trace-Return the sum along diagonals of the array.
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)



17.8026
CPU times: user 344 ms, sys: 1.86 ms, total: 346 ms
Wall time: 347 ms


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

#### Answers
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.

 * The determinant of any square matrix can be expressed as a SOPs (sum of products) of entries of the matrix where each product has n terms and the coefficient of each product is −1/1/0. An n × n matrix contributes n! terms.
 In the code these terms (n! terms) are expressed as the product of the det(permutation matrix) with the A_step1 (vectorized natural logarithm - of the form Hallow matrix) & permutation matrix.
  Summation of the average values of these n! terms will give us the determinant close to det(my_circ_matrix).
  Since the permutation matrix provides only a subset of possible solutions, output of the loop above is close to the determinant of the circulant matrix and not equal to to the determinant of the circulant matrix.
   
 * Yes, this property can extend to arbitrary matrices over real numbers. 

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [16]:
from numpy import random
import numpy as np
from scipy.linalg import det 

A = my_circ_matrix
B = np.random.randint(3, size=(3,3))
print(" A \n",A,"\n B \n",B)
print("\n Determinant of A \n",det(A),"\n","\n Determinant of B \n",det(B),"\n det(A)det(B) \n ", det(A)* det(B)) 
print("\n AB \n", np.dot(A,B),"\n Det(AB) \n", det(np.dot(A,B)))
print("\n Therefore the determinant of a matrix product of square matrices equals","\n"," the product of their determinants ")

 A 
 [[1 3 2]
 [2 1 3]
 [3 2 1]] 
 B 
 [[1 0 2]
 [0 0 2]
 [0 0 1]]

 Determinant of A 
 18.0 
 
 Determinant of B 
 0.0 
 det(A)det(B) 
  0.0

 AB 
 [[ 1  0 10]
 [ 2  0  9]
 [ 3  0 11]] 
 Det(AB) 
 0.0

 Therefore the determinant of a matrix product of square matrices equals 
  the product of their determinants 
