# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [2]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)

The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
print("Product1\n",matrix_prod1)
np.set_printoptions(suppress=True)
print("Product2\n",matrix_prod2)

Product1
 [[  6.00000000e+00+0.j           6.00000000e+00+0.j           6.00000000e+00+0.j        ]
 [ -1.50000000e+00+0.8660254j    1.50000000e+00+0.8660254j
    3.33066907e-16-1.73205081j]
 [ -1.50000000e+00-0.8660254j    1.50000000e+00-0.8660254j
   -5.55111512e-16+1.73205081j]]
Product2
 [[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 1. Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 2. Are product of circulant matrices (of a same size) always circulant matrices?
 3. Do all pairs of circulant matrices commute under matrix multiplication?

### Answers
  1. Circulant matrices are diagonalized by a discrete Fourier transform [Source](https://en.wikipedia.org/wiki/Circulant_matrix) 
  2. Circulant matrices form a commutative algebra, since for any two given matrices A and B, the sum A+B is circulant, the product, AB, is circulant, and AB=BA. [Source](https://en.wikipedia.org/wiki/Circulant_matrix#Other_properties)
  3. Yes, they form a commutitive algebra. (Same source as 2.)

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [5]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [9]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)


A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
print(A_step1)
# A_step1 = np.log(matrix_prod2)
# print(A_step1)
max_index = int(1e6)
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
#     print(permutation_matrix)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
18.031374


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explanation explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

#### Answers
1. The code uses the sign permutations of the identity matrix to approximate the determinant of a circulant matrix. Because the definition of the determinant is the sum of all possible ways of selecting entries, an infinite number of permutations will eventually converge to the determinant.  
2. The permutation approximation method extends to arbitrary matrices. 

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [7]:
import scipy as sp
# Chances of generating a singular matrix is infinitesmally small
def random_matrix(n):
    return np.random.randint(10,size=(n,n))

In [8]:
A = random_matrix(3)
B = random_matrix(3)
print("A: \n",A)
print('det(A)',sp.linalg.det(A))

print("\nB: \n",B)
print('det(B):',sp.linalg.det(B))



print("\nAB:\n",A@B)
print("det(AB):",sp.linalg.det(A@B))
print("\ndet(A)*det(B):",sp.linalg.det(A)*sp.linalg.det(B))

A: 
 [[1 4 0]
 [4 1 1]
 [3 1 9]]
det(A) -124.00000000000001

B: 
 [[6 7 5]
 [5 1 5]
 [7 3 7]]
det(B): -8.000000000000025

AB:
 [[26 11 25]
 [36 32 32]
 [86 49 83]]
det(AB): 991.9999999999992

det(A)*det(B): 992.0000000000032


* Difference between the two calculations can be accounted for through floating point precision errors in the different methods used python