# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [3]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [5]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [6]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [7]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

Answers:
    
1.Yes, circulant matrices are always diagonalized by the discrete Fourier transform matrix and its inverse, the above example shows the property.

2.Yes, the product of same size circulant matrices are always circulant matrices. The below code shows the property that AB is the curculant matric.

3.Yes, all pairs of circulant matrices commute under matric multiplication. The below code shows the property that AB=BA.

In [2]:
#Q2&Q3:
import numpy as np
from scipy.linalg import circulant

a = np.random.randint(0,5)
b = np.random.randint(10,15)
circ_matrixA = circulant([a,a+1,a+2,a+3])
circ_matrixB = circulant([b,b+1,b+2,b+3])
productAB = np.dot(circ_matrixA, circ_matrixB)
productBA = np.dot(circ_matrixB, circ_matrixA)

print('AB = ')
print(productAB)
print('BA = ')
print(productBA)

AB = 
[[162 156 162 164]
 [164 162 156 162]
 [162 164 162 156]
 [156 162 164 162]]
BA = 
[[162 156 162 164]
 [164 162 156 162]
 [162 164 162 156]
 [156 162 164 162]]


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [9]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.11688


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

Answers

1.Assume we pick the size 3 matrix, the determinant of that will be 3abc-a^3-b^3-c^3. Since the permutation matrix P is picking randomly and it has the probability of around 0.5 with 1 or -1, the sign_permution will also be 1 or -1. After we run through the code in loop we will get around 100000/factorial(3) times for our P, and our current_value is the determinant of the identity matrix. So at the end for a_step1 we get our result when we average the current_value with factorial of 3, we will get back with the value that around the determinant of identity matrix but not exactly same due to the probability of permutation matrix.  
    
2.Yes, this can be extend to arbitrary matrices over the real numbers.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [3]:
import numpy as np
from scipy.linalg import det

A = np.random.randint(10, size = (5,5))
B = np.random.randint(10, size = (5,5))
AB = np.dot(A, B)

detA = det(A)
detB = det(B)
detA_detB = np.dot(detA, detB)
det_AB = det(AB)  

print('A is')
print(A)
print('B is')
print(B)
print('det(A)det(B) is', detA_detB)
print('det(AB) is', det_AB)

if round(det_AB, 3) == round(detA_detB, 3):
    print('It is the fact that det(AB)=det(A)det(B).')
else:
    print('It is not the fact.')

A is
[[0 9 5 5 6]
 [6 1 8 3 7]
 [8 6 5 3 1]
 [0 6 1 8 1]
 [7 1 1 7 7]]
B is
[[4 3 3 9 2]
 [8 5 8 9 2]
 [2 9 6 5 1]
 [3 8 1 7 0]
 [1 9 3 0 2]]
det(A)det(B) is 104250204.0
det(AB) is 104250203.99999997
It is the fact that det(AB)=det(A)det(B).
