# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [4]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [5]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [6]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?
 
### Answers
1.Yes. Each row vector in a circulant matrix is rotated one element to the right relative to the preceding row vector. In numerical analysis, circulant matrices are  diagonalized by a discrete Fourier transform. This relationship can be discribed as 

2.Yes. The product of two circulant matrices is again circulant. Suppose A and B are two circulant matrices. A = (A1,A2,...,An) B = (B1,B2,...,Bn). Let C=AxB=(AB1,AB2,...,ABn) =(ΣAiB1,...,ΣAiBn) (i=n). Let A0=ΣAi,therefore each element in A0 is equal, denoted k. Thus, C=(kB1,...,kBn) = kB. Since B is circulant, kB is also circulant.

3.Yes. Let C = U·Ψ·U^(-1) and D = U·Φ·U^(-1), where Ψ and Φ are diagonal matrix. Thus, C·D = U·Ψ·Φ·U^(-1) and D·C = U·Φ·Ψ·U^(-1). Since Ψ·Φ = Φ·Ψ, we have C·D = D·C.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [11]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)
print(det(my_circ_matrix))

18.29076
18.0


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?
 
#### Answers
1. This example shows two different ways to calculate the determinant. The multiplication of every eigenvalue equals to the value of the determinant of the matrix. The calculation concerning the eigenvalue is shown above. If there is enough iteration, these two values should be very close.

2. This finding extend to arbitrary matrices over the real numbers. 
 

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [17]:
from numpy import random
from scipy.linalg import det
import numpy as np

n = 5 # Choose the matrix size

A = random.randint(1, 10, size=(n, n)) 
B = random.randint(1, 10, size=(n, n))
print('A=',A)
print('B=',B)

AB = np.dot(A,B)
print('AB=',AB)

Det_A = det(A)
Det_B = det(B)
Det_AB = det(AB)
print('det(A) =',Det_A)
print('det(B) =',Det_B)
print('det(AB) =',Det_AB)

Det_ADet_B=Det_A*Det_B
print('det(A) * det(B) =',Det_ADet_B)


A= [[6 6 5 2 2]
 [2 4 6 4 4]
 [6 1 3 8 4]
 [4 1 1 1 3]
 [4 8 7 3 4]]
B= [[6 8 3 9 9]
 [7 6 4 5 7]
 [4 8 4 3 1]
 [1 6 6 8 5]
 [3 7 3 3 5]]
AB= [[106 150  80 121 121]
 [ 80 140  82 100  92]
 [ 75 154  94 144 124]
 [ 45  73  35  61  64]
 [123 182 102 133 134]]
det(A) = -1002.0000000000003
det(B) = -3565.0000000000005
det(AB) = 3572129.9999999977
det(A) * det(B) = 3572130.000000002
