# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [2]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +7.51653892e-17j  0.33333333 +3.58569132e-17j
   0.33333333 -1.11022302e-16j]
 [ 0.33333333 +0.00000000e+00j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
print(matrix_prod1)
np.set_printoptions(suppress=True)
print(matrix_prod2)

[[  6.00000000e+00+0.j           6.00000000e+00+0.j           6.00000000e+00+0.j        ]
 [ -1.50000000e+00+0.8660254j    1.50000000e+00+0.8660254j
    1.11022302e-16-1.73205081j]
 [ -1.50000000e+00-0.8660254j    1.50000000e+00-0.8660254j
   -4.44089210e-16+1.73205081j]]
[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

      1.Yes, circulant matrices are always diagonalized by the discrete fourier transform matrix and its inverse, this conclusion can be found directlt from the above solution.
    2.Yes, product of circulant matrices with same size are always circulant matrices, for example if we multiply circulant matrice [1,2,3] by another circulant matrice [4,5,6] the result will be
    [[ 4 18 10]
    [10  4 18]
    [18 10  4]]  which is also a circulant matrice.
    3.Yes, all paris of circulant matrices commute under matrix multiplication, this conclusion can also be obtain by use two circulant matrices[1,2,3] and [4,5,6] which will give us the same result.


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [5]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [6]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.04164


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

    1.For det() function, the result are simply come from the equation.For a_step2, the result is In this process, random function makes permutation matrix have equal probabilities, and with a large number of max_index, we can ensure the number of each permutation matrix appears in the function are very close to each other, and this is why the two number are close to each other but not the same.

    2.This property can be used to find arbitrary matrices over real numbers, as long as permutation matrix has same proability, the result from a_step2 should always close to det()function.  



### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 28 15:17:57 2017

@author: jianfengsong
"""
import math
from numpy import random
from numpy import dot
from scipy.linalg import det

max_index=100000
true_time=0
for my_index in range(0,max_index):
    
    M_A=[[random.randint(0,10),random.randint(0,10),random.randint(0,10)],
         [random.randint(0,10),random.randint(0,10),random.randint(0,10)],
         [random.randint(0,10),random.randint(0,10),random.randint(0,10)]]
    M_B=[[random.randint(0,10),random.randint(0,10),random.randint(0,10)],
         [random.randint(0,10),random.randint(0,10),random.randint(0,10)],
         [random.randint(0,10),random.randint(0,10),random.randint(0,10)]]
   
    
    D_1=det(dot(M_A,M_B))
    D_2=det(M_A)*det(M_B)
    diff=D_1-D_2
    if (abs(diff)<0.001):
        true_time+=1
        
if true_time==max_index:
    print("det(AB)=det(A)det(B) HOLD")
else:
    print("NO")
    
    
    

det(AB)=det(A)det(B) HOLD
