# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [3]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [4]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [6]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers
1.Circulant matrices are always diagonalized by the discrete Fourier transform matrix and its inverse.
* As for a circulant matrix, its determinant is not equal to zero, so there exists at least a matrix and its inverse that can diagonalize the circulant matrix. Note the matrix as V, then $D=V^{-1}CV$, and D is a diagonalized matrix, C is the circulant matrix. V can be constructed by the eigenvectors of C, which means the columns of V are the eigenvectors of C. For a nⅹn circulant matrix, its normalized eigenvectors can be set as $v_j= \frac{1}{\sqrt{n}}[1,W^{-j},W^{-2j},…,W^{-(n-1)j}]^T$, where $W = e^{-j\frac{2π}{n}}$. We can assign $V = [v_1,v_2,…,v_n]$, then C can be diagonalized by $D=V^{-1}CV$, and the element of $V^{-1}$ is $v^{-1}_{ij} = W^{(i-1)(j-1)}$, i, j = 1,2,…,n, so $V^{-1}$ is a discrete Fourier transform matrix. As a result, a circulant matrix can always be diagonalized by the discrete Fourier transform matrix and its inverse.

2.Product of circulant matrices of a same size are always circulant matrices.
* Let A and B be nⅹn circulant matrices, and C = AB, then $c_{ij}= \sum_{r=1}^{n}a_{ir} b_{rj}$, $a_{ij}=a_{(i+1)(j-1)}$, $b_{ij}=b_{(i+1)(j-1)}$ for i ≤ n-1, j ≥ 2, $a_{i1}=a_{(i+1)n}$, $b_{i1}=b_{(i+1)n}$, therefore $c_{(i+1)(j-1)}= \sum_{r=1}^{n}a_{(i+1)r} b_{r(j-1)} = c_{ij}$, $c_(i+1n)= \sum_{r=1}^{n}a_{(i+1)r} b_{rn}= c_{i1}$, so C is also a circulant matrix.

3.All pairs of circulant matrices commute under matrix multiplication.
* Let A and B be nⅹn circulant matrices, and C = AB, D = BA, then $c_{ij}= \sum_{r=1}^{n}a_{ir}b_{rj}$, $d_{ij}= \sum_{r=1}^{n}b_{ir}a_{rj} = \sum_{r=1}^{n}b_{ri}a_{jr} = c_{ij}$ , so C = D, which means all pairs of circulant matrices commute.

  
  


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [7]:
from scipy.linalg import det
det(my_circ_matrix)
print(det(my_circ_matrix))

18.0


The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [8]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.28986


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

#### Answers
1.Explanation:
* In the code above, my_identity(denoted M) is a permutation matrix with the same size of A_step1(denoted A), and A is derived by taking the natural logarithm of every element of the circulant matrix themy_circ_matrix(denoted C). Therefore, M can be regarded as an identity matrix which has been permuted the columns or the rows, so "np.dot(A_step1, permutation_matrix)", which means AM can be regarded as permuting the columns of A. The trace of AM is the sum of the diagonal elements, and with the exponential function we can get the product of n（for this example, n = 3) elements of C, and from each row and each column of C there is only one element chosen. Regard the product as an element, according to the definition of determination, the determination of a nxn matrix is the sum of several distinct such elements with the quantity of the factorial of n. If we repeat this procedure several times, multiply every result with the factorial of n and then get the average number as the final result, because the permutation is random and the number of repeated times is very large(the max_index is 10,000), the final result can be very closely to the determination of C. Therefore, these numbers are close.

2.This property can be extended to arbitrary matrices.
* According to the explaination above, it is not necessary for C to be a circulant matrix, and this  property can be extended to arbitrary matices.


### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [26]:
import numpy as np
from numpy import random
from scipy.linalg import det

#******** Set the random matrices A and B of random size**********
n = np.random.randint(2,10) #set the size of the matrices
A = np.random.rand(n,n)  
B = np.random.rand(n,n) 
#************************** get det(AB)***************************
AB =  np.dot(A, B)
det_AB = det(AB)
#*********************** get det(A)det(B)*************************
det_A = det(A)
det_B = det(B)
detA_detB = det_A * det_B
#****************** ***** show the result*************************
print("The size of A and B is",n,"X",n)
print("A = ",A)
print("B = ",B)
print("det(AB) = ",det_AB)
print("det(A)det(B) = ",detA_detB)

The size of A and B is 8 X 8
A =  [[ 0.18386521  0.76624046  0.77199193  0.17568613  0.30310039  0.17570214
   0.92317376  0.47427603]
 [ 0.31575717  0.56972932  0.50663145  0.32353328  0.19909258  0.28567419
   0.90595443  0.10227745]
 [ 0.61839228  0.78558443  0.42565611  0.10680854  0.25009443  0.47366
   0.70395728  0.63770361]
 [ 0.37574369  0.68260691  0.39005426  0.4704932   0.50465834  0.8394134
   0.31390929  0.47699566]
 [ 0.09537893  0.70439919  0.70575168  0.91433706  0.88066887  0.41911174
   0.03365695  0.04813303]
 [ 0.26594519  0.93991277  0.85557035  0.21664333  0.01414939  0.32132738
   0.89925518  0.9882489 ]
 [ 0.9139292   0.87671152  0.98172094  0.629992    0.3145409   0.34560787
   0.00373325  0.62705233]
 [ 0.67449755  0.63617259  0.17377227  0.05669343  0.8062748   0.01336837
   0.40615239  0.04615037]]
B =  [[ 0.2697076   0.08176978  0.39240548  0.77803146  0.83108296  0.83182049
   0.89208127  0.2371994 ]
 [ 0.20768298  0.69379041  0.47446736  0.30022244  0.96

By running this code several times, I can verify that the determinant function is multiplicative, which means $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.