# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [16]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [17]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [18]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333+0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [19]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0+0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answer

1. Yes, $F^{-1}AF = FAF^{-1} = diag(A)$

2. Yes, multiplication is commutative

3. Yes


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [20]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [22]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

17.62806


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

### Answer

1.
<br>
In this case the matrix is 3x3, so my_identity is $ eye(3)$.
<br>
A permutation matrix is a matrix obtained by permuting the rows of an n×n identity matrix according to some permutation of the numbers 1 to n. A permutation matrix is nonsingular, and the determinant is always +/-1. That's to say, sign_permuation is +/-1.
<br>
np.dot(A_step1, permutation_matrix) gives the matrix A_step1 with rows interchanged according to the permutation vector. 
<br>
np.trace returns the sum along diagonals. That's to say, np.trace(np.dot(A_step1, permutation_matrix)) has only 6 values which are 0, 1.79175946923, 1.79175946923, 1.79175946923, 2.07944154168, 3.295836866
<br>
Therefore value of sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix)))) also can only be 1, -6, -6, -6, 8, 27.
<br> 
Finally, the result a_step2 is taking avg, and its value should be around (1-6-6-6+8+27)/6=18. The larger the max_index is, the closer the result will be 18.
<br>
<br>
2.
<br>
The property extends to artitrary matrices over the real numbers. This is because limited combinations of permutation matrices determine limited values of "current_value". So the final result a_step2 will always be around a constant.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [33]:
from numpy import random
from scipy.linalg import det

n=random.randint(2,10)
print("Matrix is ",n,"*",n)
a=random.rand(n,n)
print("Matrix A is :")
print(a)
print()
b=random.rand(n,n)
print("Matrix B is :")
print(b)
print()

detA=det(a)
detB=det(b)
ab=np.dot(a,b)
print("Matrix AB is :")
print(ab)
print()
detAB=det(ab)

print("det(AB) = ", detAB)
print("det(A)det(B) = ", detA*detB)

Matrix is  7 * 7
Matrix A is :
[[ 0.80861317  0.67022668  0.93323331  0.6231779   0.48152293  0.40381919
   0.36281443]
 [ 0.93821319  0.48188205  0.69676039  0.23148466  0.99780777  0.79910131
   0.09376624]
 [ 0.30414742  0.1458256   0.91158637  0.90446039  0.12885762  0.68549843
   0.17577672]
 [ 0.08698616  0.05079222  0.30537059  0.14017467  0.03142864  0.21038606
   0.76241667]
 [ 0.86338335  0.13738419  0.24150053  0.72045316  0.86386878  0.13545912
   0.84276924]
 [ 0.75055507  0.19885884  0.67479705  0.70682631  0.52125195  0.92482421
   0.66813862]
 [ 0.6563896   0.23391123  0.66043747  0.61081468  0.35645757  0.24254396
   0.02995302]]

Matrix B is :
[[ 0.13925551  0.77232499  0.51013111  0.61997629  0.11661299  0.72853307
   0.76614223]
 [ 0.65889741  0.10271318  0.83580327  0.06125411  0.68212566  0.56839034
   0.58780633]
 [ 0.37511281  0.62694251  0.01875532  0.90010833  0.9770251   0.36245237
   0.23767399]
 [ 0.18637211  0.17550555  0.80209056  0.13775069  0.88312976  

### Result

Determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.