# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [1]:
import numpy as np
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
product_my_circ_matrix=np.dot(my_circ_matrix,my_circ_matrix)
print (my_circ_matrix)
print (product_my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]
[[13 10 13]
 [13 13 10]
 [10 13 13]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [2]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print (my_dft_matrix)


[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

Answers:
1. Yes, it is shown above and it is the property of circulant matrices.
2. Yes, it can be shwon above. The product of my_circ_matrix and my_circ_matrix is also a circulant matrix. 
3. Yes, AB=BA for circulant matrices.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [10]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)
print(A_step1)
max_index = 100000
my_identity = np.identity(len(A_step1))
print(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
3
18.14622


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

Answers:
    1. First, the code gets the natural logarithm of the original matrix and initializes the identity matrix with the same size of the original matrix.
Second, it uses a loop to calculate the current value by rearranging the identity matrix and getting its determinant.
Third, it gets the average of the result.
The code uses the algorithm that the determinant of this matrix is just the multiplication of every eigenvalue.
        2. Yes, it is a way to calculate the determinant of circulant 2-D matrix.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [25]:
from scipy.linalg import det
from numpy import random
import numpy as np
import math
matrix1 = random.randint(1,100,size=(4,4))
matrix2 = random.randint(1,100,size=(4,4))
print('Matrix A is: ')
print(matrix1)
print('Matrix B is: ')
print(matrix2)
print("Determinant of AB is :",det(np.dot(matrix1,matrix2)))
print("Determinant of A * determinat of B is :",det(matrix1) * det(matrix2))

Matrix A is: 
[[94 95 22 51]
 [73 29 53 47]
 [33 65 24 47]
 [57 12 14 63]]
Matrix B is: 
[[38 18 65 55]
 [29 48 25 12]
 [35 20 42  5]
 [94 97 46 63]]
Determinant of AB is : 35489864409860.04
Determinant of A * determinat of B is : 35489864409860.0


So, as we can see from the result, det(AB)=det(A)det(B)