# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [5]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [6]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [7]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333+0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [9]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j         0.0+0.j        -0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers
1. Circulant matrices are always diagnolized by the discrete Fourier transform matrix and its inverse.

  The normalized eigenvectors of a N dimensional circulant matrix is 
  \begin{equation}
  v_j=\frac{1}{\sqrt{N}}\left(1,w_j,w_j^2,\cdots ,w_j^{N-1}\right)^T, ~~~~ j=0,1,\cdots,N-1
  \end{equation}
  where, $w_j=\exp{\left(\frac{2\pi ij}{N}\right)}$and $i$ is the imaginary unit.
  
  If we form the eigenvectors as a basis and built them into a matrix $P$, then $P^{-1}CP$ will be a diagonal matrix.
  
  As we know. the $N\times N$ square DFT matrix $W$ is
  \begin{equation}
  W=\frac{1}{\sqrt{N}}
  \left[\begin{array}{cccccc}
  1 & 1 & 1 & 1 & \cdots & 1 \\
  1 & w & w^2 & w^3 & \cdots & w^{N-1} \\
  1 & w^2 & w^4 & w^6 & \cdots & w^{2\left(N-1\right)} \\
  1 & w^3 & w^6 & w^9 & \cdots & w^{3\left(N-1\right)} \\
  \vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
  1 & w^{N-1} & w^{2\left(N-1\right)} & w^{3\left(N-1\right)} & \cdots & w^{\left(N-1\right)\left(N-1\right)}
  \end{array}\right]
  \end{equation}
  where the colomn vectors are the same as the normalized eigenvectors of a N dimensional circulant matrix. 
  
  Then, we have $P=W$ and $W^{-1}CW$ is a diagonal matrix. 
  
  So, circulant matrices are always disgnolized by the discrete Fourier transform matrix and its inverse. 

2. The product of circulant matrices are always circulant matrices.

3. All pairs of circulant matrics commute under matrix multiplication.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [12]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [15]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

print(my_circ_matrix)
A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
print(A_step1)
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

[[1 3 2]
 [2 1 3]
 [3 2 1]]
[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
17.75514


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

### Answers
1. Let $C$=my_circ_matrix=$\left[\begin{array}{ccc}a & c & b\\b & a & c\\c & b & a\end{array}\right]$,then A_step1=$\left[\begin{array}{ccc}\ln{a} & \ln{c} & \ln{b}\\\ln{b} & \ln{a} & \ln{c}\\\ln{c} & \ln{b} & \ln{a}\end{array}\right]$, $\det{\left(A\right)}=\left|\begin{array}{ccc}a & c & b\\b & a & c\\c & b & a\end{array}\right|=a\left(a^2-bc\right)-c\left(ab-c^2\right)+b\left(b^2-ac\right)=a^2+b^2+c^2-3abc$.
  
  The random.permutation(my_identity) has 6 diffrents situations which are of the same probability.
  
  When permutation_matrix = random.permutation(my_identity) = $\left[\begin{array}{ccc}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{array}\right]$, sign_permuation = det(permutation_matrix) = 1, np.dot(A_step1, permutation_matrix) = $\left[\begin{array}{ccc}\ln{a} & 0 & 0\\0 & \ln{a} & 0\\0 & 0 & \ln{a}\end{array}\right]$, np.trace(np.dot(A_step1, permutation_matrix)) = $3\ln{a}$, np.exp(np.trace(np.dot(A_step1, permutation_matrix))) = $a^3$, current_value += $a^3$.
  
  The same, when permutation_matrix = $\left[\begin{array}{ccc}1 & 0 & 0\\0 & 0 & 1\\0 & 1 & 0\end{array}\right]$ or $\left[\begin{array}{ccc}0 & 1 & 0\\1 & 0 & 0\\0 & 0 & 1\end{array}\right]$ or $\left[\begin{array}{ccc}0 & 0 & 1\\0 & 1 & 0\\1 & 0 & 0\end{array}\right]$, we have current_value += $-abc$.
  
  When permutation_matrix = $\left[\begin{array}{ccc}0 & 1 & 0\\0 & 0 & 1\\1 & 0 & 0\end{array}\right]$, we have current_value += $b^3$.
  
  When permutation_matrix = $\left[\begin{array}{ccc}0 & 0 & 1\\1 & 0 & 0\\0 & 1 & 0\end{array}\right]$, we have current_value += $c^3$.
  
  Due to the 6 kinds of permutation_matrix appear at a probability of $\frac{1}{6}$ of each, a_step2 = 6 * current_value / max_index is equal to $a^2+b^2+c^2-3abc$ when max_index is infinite which is equal to $\det{\left(A\right)}$.
  
2. It can be extended to arbitrary matrices over the real numbers.
  
  Because np.exp(np.trace(np.dot(A_step1, permutation_matrix))) is one of the items that including in the determinant calculation and sign_permuation = det(permutation_matrix) is actually the sign of this item. 
  
  This process randomly sums up all the items in determinant calculation and calculates the mean which is equal to the determinant when repeats infinite times.
  

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [26]:
A = random.randint(1, 10 + 1,(5,5))
B = random.randint(1, 10 + 1,(5,5))
AB = np.dot(A,B)
print("A=",A)
print("B=",B)
print("AB=",AB)

A= [[ 7 10  5 10  5]
 [ 4  7  9  3  6]
 [ 8  1  4  1  8]
 [ 1  3 10  4  4]
 [ 3  6  1  8  8]]
B= [[10  2  5 10  5]
 [ 7  8  3  8  8]
 [10  4  7  1  7]
 [ 2  5  6  6  5]
 [10  7  5  7  6]]
AB= [[260 199 185 250 230]
 [245 157 152 165 190]
 [209 101 117 154 129]
 [179 114 128  96 143]
 [178 154 128 183 158]]


In [27]:
detA = det(A)
detB = det(B)
detAdetB = detA * detB
detAB = det(AB)
print("det(A)=",detA)
print("det(B)",detB)
print("det(A)*det(B)=",detAdetB)
print("det(AB)=",detAB)

det(A)= 22365.000000000004
det(B) -9678.000000000002
det(A)*det(B)= -216448470.0000001
det(AB)= -216448470.00000072


In [28]:
if(abs(detAdetB - detAB) < 0.0001):
    print("det(A)det(B) = det(AB)")
else:
    print("det(A)det(B) is not equal to det(AB)")

det(A)det(B) = det(AB)
