# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [4]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [5]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [6]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +2.77555756e-17j  0.33333333 +2.77555756e-17j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [7]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0-0.j         0.0+0.j        -0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

### Answers
1. Yes. $X=F*diag(x)*F^H$. It is the property of circulant matrices.
2. Yes. If we assume $C=A*B$ and $A B$ are circulant matrices, we can know $C = [A0B1,……,A0Bn]$ and $A0$ is the vector of the sum of every element in colunm. Because $A$ is a circulant matrix, we can assume $A0$ is equal to a constant $k$. And then, $C=[kB0,...,kBN]=kB$. Bacause $B$ is a circulant matrix, $C$ is also a circulant matrix.  
3. Yes. It is known that there is a matrix $T$ whose columns are $v1,…,vnv1,…,vn$ such that $T-1AT=DAT-1AT=DA$ and $T-1BT=DBT-1BT=DB$ are diagonal matrices. Since $DA$ and $DB$ trivially commute (explicit calculation shows this), we have $AB=TDAT-1TDBT-1=TDADBT-1=TDBDAT-1=TDBT-1TDAT-1=BA.$


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [9]:
import math
from numpy import random
import numpy as np

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.05118


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

#### Answers
1. It is because of different way to calculate det(A). For $n*n$ matrix, the result that every eigenvalue multiply together is equal to the valur of determinant of the matrix. First, the program uses $log$ to transform "multiply" to "plus". Sencond, because circulant matrix is being calculated, we can know that trace(A) is approximately equal to eigenvalue. $sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))$ is used to calculate the sum of transformed eignevalue and transform the "plus" to "multiply". If we want to get more precise value, we need to make the loop bigger. Finally, the program gains the average of the result.
2. It is specific way to calculate the determinant of circulant matrix, because circulant matrix's eigenvalue can be gained by other ways. However, it can be only used in 2-D matrix. The function $np.trace$ will return the diagonal but, for other dimensions, it will return the arrary of diagonals. Bacause we don't know the property of larger dimensions matrix, we cannot calculate the eigenvalue. So we cannot get the determinant of matrix.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [2]:
from numpy import random
from scipy.linalg import det
import numpy as np
##determine the size of matrix
n=random.randint(2,8)
print('matrix size is ',n,'*',n)
##print metrix A B
a=random.randint(1,100,size=(n,n))
print('matrix A is :')
print(a)
b=random.randint(1,100,size=(n,n))
print('matrix B is :')
print(b)
##calculate det(A) det(B) det(AB) and distance between two results
ab=np.dot(a,b)
print('matrix AB is:')
print(ab)
det_a=det(a)
det_b=det(b)
det_ab=det(ab)
print('det(AB) =',det_ab)
print('det(A)*det(B)=',det_a*det_b)
print('the distance is',abs(det_ab-det_a*det_b))


matrix size is  4 * 4
matrix A is :
[[ 7 65 88 71]
 [81 14 26 20]
 [ 3 23 32 85]
 [82 51 50 79]]
matrix B is :
[[87 77  4  9]
 [57 29 47 99]
 [32 50 31 58]
 [33 44 81 24]]
matrix AB is:
[[ 9473  9948 11562 13306]
 [ 9337  8823  3408  4103]
 [ 5401  6238  8970  6200]
 [14248 13769 10674 10583]]
det(AB) = -151600345847135.94
det(A)*det(B)= -151600345847135.97
the distance is 0.03125


### Conclusion
Comparing with two results, the distance is too small. So the determinant function is multiplicative.