# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [7]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [8]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [9]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333-0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [10]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)
matrix_prod3 = np.dot(my_circ_matrix, my_circ_matrix)


np.set_printoptions(suppress=True)

print(matrix_prod2)
print(matrix_prod3)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]
[[13 10 13]
 [13 13 10]
 [10 13 13]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

________________________________________________________________________________________________________________________________

##### (1) Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?

________________________________________________________________________________________________________________________________

  Yes, circulant matrices are always diagonalized by the discrete Fourier transform matrix and its inverse.
  Reference(https://en.wikipedia.org/wiki/Circulant_matrix). 
  
  Circulant Matrices has the following property.
  
  $C = F_{m}^{-1}(D)F_{m}$
  
  $C$ is the circulant matrix and $F_{m}$ is the DFT transform matrix.
  where $(D)$ is defined to be
  
  $(D) = diag(F_{m}c)$       
  
  This is the diagonal matrix containing eigenvalues c(fisrt columns of C), where C(Circulant Matrix), F(DFT matrix) is define to be the following:
    
$C=\left[ \begin{array}{cccc}
C_{0} & C_{M-1} & \ldots & C_{1} \\
C_{1} & C_{0} & \ldots & C_{2} \\
\vdots & \vdots &        & \vdots \\
C_{M-1} & C_{M-2} & \ldots & C_{0} \\ \end{array} \right]$         $F=\left[ \begin{array}{cccc}
1 & 1 & 1 & 1 \\
1 & w^{1} & \ldots & w^{(M-1)} \\
1 & w^{2} & \ldots & w^{2(M-1)} \\
\vdots & \vdots &        & \vdots \\
1 & w^{M-1} & \ldots & w^{2(M-1)} \\ \end{array} \right]$ 

and $w = e^{2\pi(i)/m}$, $i=\sqrt{-1}$

  This property shows that the Circulant Matrix is a function of Diagonal matrix with its eugenvalues and DFT matrices inverse and itself.



________________________________________________________________________________________________________________________________

##### (2) Are product of circulant matrices (of a same size) always circulant matrices?
________________________________________________________________________________________________________________________________

Yes, product of circulant matrices are always circulant matrices. This is due to the fact that every circulant matrices has eigenvectors which contains eigenvalues. And product of two circulant matrices preserves its eigenvalues in thier matrices. This means that the eigenvetors are preserved as well.



________________________________________________________________________________________________________________________________

##### (3) Do all pairs of circulant matrices commute under matrix multiplication?
________________________________________________________________________________________________________________________________

Yes, All pairs of circulant matrices commute under matrix muptiplicaiton. Eigenvalues are defined as: $eigenvalues = (e^{-2\pi(j)(k)(i)/n})$, and this is contained in eigenvectors. The communting the matrices still contains diagonal matrices with these eigenvalues.

When A and B are both circulant matrices. The following equation defines them as mentioned in 2nd part of the question.

  $A = F_{m}^{-1}(D_{1})F_{m}$
  
  $B = F_{m}^{-1}(D_{2})F_{m}$
  
We can see that 

  $AB = F_{m}^{-1}(D_{1})(D_{2})F_{m} = BA$

and $(D_{1})(D_{2})$ are diagonal matrix with eigenvetors containging $eigenvalues = (e^{-2\pi(j)(k)(i)/n})$. This implies that $AB$ and $BA$ are commutative and it is circulant.





## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [11]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [22]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

print(A_step1)

max_index = 100000
my_identity = np.identity(len(A_step1))
print(my_identity)

current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(current_value)
print(a_step2)

[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
296109.0
17.76654


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

##### (1) Go through the code and provide a compelling explanation of why these numbers are close.

The code above is computing the determinant of the matrix, utilizing the linearity of the matrix. In other words, the code is utilizing the fact that the matrix can be expressed in terms of finite linear combination of diffrent matrices. 

For example,
$C=\left[ \begin{array}{cccc}
C_{11} & C_{12} & \ldots & C_{1n} \\
C_{12} & C_{22} & \ldots & C_{2n} \\
\vdots & \vdots &        & \vdots \\
C_{m1} & C_{m2} & \ldots & C_{mn} \\ \end{array} \right]$

can be expressed in terms of linear combination as follows

$C_{11}*\left[ \begin{array}{cccc}
1 & 0 & \ldots & 0 \\
C_{12} & C_{22} & \ldots & C_{2n} \\
\vdots & \vdots &        & \vdots \\
C_{m1} & C_{m2} & \ldots & C_{mn} \\ \end{array} \right] + C_{12}*\left[ \begin{array}{cccc}
0 & 1 & \ldots & 0 \\
C_{12} & C_{22} & \ldots & C_{2n} \\
\vdots & \vdots &        & \vdots \\
C_{m1} & C_{m2} & \ldots & C_{mn} \\ \end{array} \right] + ... + C_{1n}*\left[ \begin{array}{cccc}
0 & 0 & \ldots & 1 \\
C_{12} & C_{22} & \ldots & C_{2n} \\
\vdots & \vdots &        & \vdots \\
C_{m1} & C_{m2} & \ldots & C_{mn} \\ \end{array} \right]$

Each row can be composed of linear comibation of different matrices. These different component matrix also could be expressed in terms of permutation matrix as well. And these permutation matrices either has the determinant of 1,-1. 

Example of the $(3 x 3)$ permutation matrix is as follows.

$P=\left[ \begin{array}{cccc}
1 & 0 & 0 \\
0 & 0 & 1 \\
0 & 1 & 0 \\ 
 \end{array} \right]P=\left[ \begin{array}{cccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\ 
 \end{array} \right]P=\left[ \begin{array}{cccc}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0 \\ 
 \end{array} \right]P=\left[\begin{array}{cccc}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \\ 
 \end{array} \right]P=\left[\begin{array}{cccc}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\ 
 \end{array} \right]$

And Summation of these series of permutation multiplied with computed sign will result is the determinant of the matrix.
The code is computing its determinants by summing all possible permutation and sign taken over its matrix.



##### (2) Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

This finding could be extend to arbitrary matrices over the real numbers. because determinants are computed with product of elements in the matrix and there are n! ways of selecting the element out of each row and columns. And this applies to all arbitrary matrices. These element selections are determined by the permutation of the matrix.

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [1]:
import numpy as np
from scipy.linalg import det

a = np.matrix('2 2 5; 3 1 3; 2 5 1')
b = np.matrix('1 4 3; 2 2 1; 2 3 3')


AB=a*b
print(AB)

Det_AB=det(AB)
print(Det_AB)

Det_A=det(a)
Det_B=det(b)
print(Det_A*Det_B)

[[16 27 23]
 [11 23 19]
 [14 21 14]]
-301.0
-301.0
