# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [12]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [13]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [14]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333-0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [15]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod1)
print(matrix_prod2)

[[ 6.0+0.j          6.0+0.j          6.0+0.j        ]
 [-1.5+0.8660254j   1.5+0.8660254j   0.0-1.73205081j]
 [-1.5-0.8660254j   1.5-0.8660254j  -0.0+1.73205081j]]
[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?
 
 Answer
 1. Yes, the circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse
 f∙c∙inc(f)=digonal metric. we can see from the programming result.
 2. Yes, since the product of two circulant matrices (of a same size) follow the  algebraic algorithm. A B have same size, so C=AB also hse the same size of A and B matric according to algebraix algorithm.
 3. Yes, according to the algebraic algorithm, all pairs of circulant matrices commute under matric multiplication. Like A=circulant[a,b,c] B=circulant[x,y,z] AB=[[ax+bz+cy az+by+cx ay+bx+cz][ay+bx+cz ax+bz+cy az+by+cx][ az+by+cy ay+bx+cz ax+bz+cy]]=BA

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [16]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [17]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)

max_index = 100000
my_identity = np.identity(len(A_step1))
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)

18.0117


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?
 Answer
 1 for the determinant of circulant matrix, it caluclate the determinand of matrix according to algebraic, which det(A)=det(circulant[1,2,3])=1^3+2^3+3^3-3*(1*2*3)=18
   for the output of loop, result is caclulated by the function： 
   a_step2 = (sum{det(permutation_matrix)exp(trace(ln(my_circ_matrix))[permutation_matrix])}) *3!)/max_index where permutation_matrix is randomly generated and it has 6 different permutations as below: 
   [[1 0 0];[0 1 0];[0 0 1]] [[1 0 0];[0 0 1];[0 1 0]] [[0 1 0];[0 0 1];[1 0 0]] [[0 1 0];[1 0 0];[0 0 1]] [[0 0 1];[0 1 0];[1 0 0]] [[0 0 1];[1 0 0];[0 1 0] ]
   random function inside for loop, makees the permutations have equal probabilities only the loop have enough times(like in the code index=100000). if the max_index is simplified to 6 probability will be 3:1:1:1, then we will have each permutation of "P" occurs as previous. This results in the formula to get the value of a_step2 = a^3+b^3+c^3 - 3.a.b.c, which is equal to the determinant value of the circular matrix, and a_step2 = 3!*18/6 = 18.0 However, probability of the 6 permutations is not exactly equal=3:1:1:1. but approximately equal, hence the numbers(index=100000) are very close enough.


 2 Yes, it is. Because the arbitary matrices depend on the probability of occurence of when the permutations mentioned above and np.trace(np.dot(A_step1, permutation_matrix)) values to be the same. So the results will be same. 

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [18]:
import numpy as np
from scipy.linalg import det

n=np.random.randint(3,10)

A=np.zeros((n,n))
B=np.zeros((n,n))

for i in range(0,n,1):
    for j in range(0,n,1):
        A[i,j]=np.random.randint(1,10)
        B[i,j]=np.random.randint(1,10)
        
AB=np.dot(A, B)
X=det(AB)
Y=det(A)*det(B)

print("A= ",A)
print("B= ",B)
print("det(AB)=", X)
print("det(A)*det(B)= ",Y)




A=  [[ 5.  1.  2.  8.  4.  7.  8.]
 [ 3.  7.  1.  9.  9.  8.  7.]
 [ 3.  9.  6.  7.  5.  3.  8.]
 [ 9.  5.  4.  3.  2.  3.  4.]
 [ 6.  5.  7.  8.  8.  7.  9.]
 [ 4.  7.  8.  7.  9.  9.  9.]
 [ 7.  4.  1.  1.  8.  3.  2.]]
B=  [[ 1.  4.  5.  4.  8.  2.  4.]
 [ 3.  7.  7.  1.  9.  7.  8.]
 [ 3.  2.  9.  6.  8.  4.  4.]
 [ 5.  8.  4.  2.  5.  9.  3.]
 [ 7.  6.  3.  8.  4.  9.  8.]
 [ 4.  4.  6.  7.  2.  6.  3.]
 [ 3.  3.  3.  9.  8.  3.  5.]]
det(AB)= -4882769207.999961
det(A)*det(B)=  -4882769207.999997


In [19]:
#### As shown in the result, the determinant function is multiplicative.