# Challenge 2
1 An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [7]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])

my_circ_matrix2 = circulant([4,5,6])

my_circ_matrix3 = np.dot(my_circ_matrix,my_circ_matrix2) 

my_circ_matrix4 = np.dot(my_circ_matrix2,my_circ_matrix)


print(my_circ_matrix)
print(my_circ_matrix2)
print(my_circ_matrix3)# this is to verify the question2
print(my_circ_matrix4)# this is to verify question 3, if my_circ_matrix3=my_circ_matrix4,then question3 is correct.

[[1 3 2]
 [2 1 3]
 [3 2 1]]
[[4 6 5]
 [5 4 6]
 [6 5 4]]
[[31 28 31]
 [31 31 28]
 [28 31 31]]
[[31 28 31]
 [31 31 28]
 [28 31 31]]


In [1]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)


[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


In [3]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333 +6.21949886e-17j  0.33333333 -6.68383741e-18j
   0.33333333 -5.55111512e-17j]
 [ 0.33333333 +5.55111512e-17j -0.16666667 +2.88675135e-01j
  -0.16666667 -2.88675135e-01j]
 [ 0.33333333 -1.11022302e-16j -0.16666667 -2.88675135e-01j
  -0.16666667 +2.88675135e-01j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [4]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

Answers:
1: YES. It is shown above that only the diagonal elements are not zero and the other elements are zero, so circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse
2: YES. It is shown above that my_circ_matrix3 is a circulant matrice.
3: YES. It is shown above that my_circ_matrix3=my_circ_matrix4,indicating paies of circulant matrices commute under matrix multiplication.

## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [8]:
from scipy.linalg import det
det(my_circ_matrix)

18.0

The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [16]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)
print(A_step1)

max_index = 100000
my_identity = np.identity(len(A_step1))  # get a identity matrix
current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity)
    sign_permuation = det(permutation_matrix)  # either 1 or -1
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix))))
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)


[[ 0.          1.09861229  0.69314718]
 [ 0.69314718  0.          1.09861229]
 [ 1.09861229  0.69314718  0.        ]]
18.08322


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?

Answers:
1 det(my_circ_matrix)=18
  By using my_identity = np.identity(len(A_step1)),we have an identity matrix and the permutation_matrix has six different types with their det be either 1 or -1.
  
  Then we consider the np.trace(np.dot(A_step1, permutation_matrix)) ,it may have four values: 1.79175946923, 0.0, 3.295836866, 2.07944154168 with the possibility of 1/2,1/6,1/6,1/6 respectively. Then sign_permuation*np.exp(np.trace(np.dot(A_step1, permutation_matrix)))may be -6,1,27,8 respectively.So if max_index=6,current_value should be (-6)*3+1+27+8=18.
 
 Finally,a_step2=3!*18/6=18. 
  
  The reason why some small differences exist is the possibility isn't the same as said above and 100000 cannot be divided exactly by 6.
 

2  Yes. This property would extend to arbitrary matrices over the real numbers
   The result is related to the time that each permutation metrice's showing up. if the max_index is large enough, then the result is the same as the det of my_circ_matrix.


### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [17]:
import numpy as np
from scipy.linalg import det
from numpy import random
matrix1 = random.randint(1,20,size=(5,5))
matrix2 = random.randint(1,20,size=(5,5))
print('Matrix 1 is: ')
print(matrix1)
print('Matrix 2 is: ')
print(matrix2)
print("Det AB is :",det(np.dot(matrix1,matrix2)))
print("Det of A * det of B is :",det(matrix1) * det(matrix2))


Matrix 1 is: 
[[16 11  8 16 16]
 [ 5 18 12  9 16]
 [ 4 12 15  2  8]
 [12  1 17 15 13]
 [ 7 10  9  1  2]]
Matrix 2 is: 
[[ 7 11  8  9 18]
 [ 8 12  7 11  4]
 [19 13 19  8  2]
 [ 1  5 12 17  1]
 [19 17  5  1  5]]
Det AB is : 2140735388.0000005
Det of A * det of B is : 2140735387.9999993


So the determinant function is multiplicative.