# Challenge 2
An important aspect of pragmatic vector space methods is the ability to handle vectors and matrices.
A large collection of linear algebra functions is available in [SciPy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html).
These functions can be employed in conjunction with the tools available in [NumPy](http://www.numpy.org/).
We note that the main object in NumPy is the homogeneous multidimensional array.

## Matrix
We begin by creating a simple matrix.
One possible approach to complete this task is to use ```scipy.linalg.circulant(c)```.

In [51]:
from scipy.linalg import circulant
my_circ_matrix = circulant([1, 2, 3])
print(my_circ_matrix)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


Alternatively, you can construct the familiar discrete Fourier transform matrix with ```scipy.linalg.dft(n)```.

In [52]:
from scipy.linalg import dft
my_dft_matrix = dft(3)
print(my_dft_matrix)

[[ 1.0+0.j         1.0+0.j         1.0+0.j       ]
 [ 1.0+0.j        -0.5-0.8660254j -0.5+0.8660254j]
 [ 1.0+0.j        -0.5+0.8660254j -0.5-0.8660254j]]


The inverse of a matrix can be computed using ```scipy.linalg.inv(a)```.

In [53]:
from scipy.linalg import inv
my_idft_matrix = inv(my_dft_matrix)
print(my_idft_matrix)

[[ 0.33333333+0.j          0.33333333-0.j          0.33333333-0.j        ]
 [ 0.33333333+0.j         -0.16666667+0.28867513j -0.16666667-0.28867513j]
 [ 0.33333333-0.j         -0.16666667-0.28867513j -0.16666667+0.28867513j]]


The operation ```numpy.dot(a, b)``` computes the dot product of two arrays.
For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation).

In [54]:
import numpy as np
matrix_prod1 = np.dot(my_dft_matrix, my_circ_matrix)
matrix_prod2 = np.dot(matrix_prod1, my_idft_matrix)

np.set_printoptions(suppress=True)
print(matrix_prod2)

[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


### Questions
These steps and their solutions immediately bring up three questions.
 * Are circulant matrices always diagonalized by the discrete Fourier transform matrix and its inverse?
 * Are product of circulant matrices (of a same size) always circulant matrices?
 * Do all pairs of circulant matrices commute under matrix multiplication?

Answer : 1. Circulant matrices property states that the elements in consecutive rows are right shifted to form a square matrix. In case of DFT, the matrix is the elements of nth root of 1 ordered precisely to perform DFT for a given vector.They form the right eigen vectors for circular matrix.. Inverse DFT matrix is the complex conjugate matrix of DFT matrix and hence the inverse DFT form left Eigen Vector of Circular Matrix.By definition of eigen vectors, we understand that they can be replaced by equivalent scalars, in this case the scalars are the diagonal elements of the digonal matrix. 
Hence Its always possible for DFT to diagonalize a given circular matrix 




In [55]:
# for checking if the product of circular matrix is also circulant. 
# approach is to multiply two circular matrices and check if they are diagonizable 
my_circ_matrix_2 = circulant([4, 5, 6])
np.set_printoptions(suppress=True)

resultant_matrix = np.dot(my_circ_matrix,my_circ_matrix_2)
print(resultant_matrix)
# checking if its diagonizable
matrix_prod3 = np.dot(my_dft_matrix, resultant_matrix)
matrix_prod4 = np.dot(matrix_prod3, my_idft_matrix)
np.set_printoptions(suppress=True)
print(matrix_prod2)

[[31 28 31]
 [31 31 28]
 [28 31 31]]
[[ 6.0+0.j        -0.0+0.j         0.0+0.j       ]
 [-0.0-0.j        -1.5+0.8660254j -0.0-0.j       ]
 [ 0.0-0.j         0.0-0.j        -1.5-0.8660254j]]


Answer : Two Obeservations can be drawn
1. By obeserving the resultant matrix of two circular multiplications, we find that the resultant matrix also circular. 
2. For confirmation, we diagonalize the resultant matrix with fourier transform to find that the final matrix is truly diagonal.
Hence the conclusion can be drawn that the product of two cicurlar matrices are always circular.


In [56]:
# check if commutative law is satisfied for the cirular matrices under multiplication.
# approach is by performinig  the direct multiplication of two circular matrices Aand B and verifying if AB=BA

#AXB
first_matrix = np.dot(my_circ_matrix,my_circ_matrix_2) 
second_matrix = np.dot(my_circ_matrix_2,my_circ_matrix)


np.set_printoptions(suppress= True)
print(first_matrix)
print(second_matrix)
print("the commutation under circular matrix is ",np.allclose(first_matrix,second_matrix))


[[31 28 31]
 [31 31 28]
 [28 31 31]]
[[31 28 31]
 [31 31 28]
 [28 31 31]]
the commutation under circular matrix is  True


## Determinant
The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix, and it summarizes a multivariable phenomenon with a signle number.
It can be computed with ```scipy.linalg.det(a)```.

In [57]:
from scipy.linalg import det
x= det(my_circ_matrix)
print(x)

18.0


The code below demonstrates how to create a function in Python, how to vectorize a function so that it can be applied to the elements of a matrix, and how to use ```random```.

In [59]:
import math
from numpy import random

def my_log(x):
    return math.log(x)

my_vec_log = np.vectorize(my_log)

A_step1 = my_vec_log(my_circ_matrix) # Numpy already offers a vectorized natural logarithm.
# A_step1 = np.log(matrix_prod2)
#print(A_step1)

max_index = 10000
my_identity = np.identity(len(A_step1)) # this gives the n*n identity matrix


current_value = 0.0
for my_index in range(0, max_index):
    permutation_matrix = random.permutation(my_identity) # permutation matrix to is randomly generated, hence it takes random distribution
    sign_permuation = det(permutation_matrix) # determinant of permutation matrix is always 1/-1
#     print(det(permutation_matrix))
    current_value += sign_permuation*(np.exp(np.trace(np.dot(A_step1, permutation_matrix)))) 
a_step2 = math.factorial(len(A_step1)) * current_value / max_index
print(a_step2)


18.2598


#### Questions
It appears that the output of the loop above is close to the determinant of the circulant matrix ```my_circ_matrix```.
 * Go through the code and provide a compelling explain explanation of why these numbers are close.
 
 Answer : 
     The code performs the following actions:
     1. Before entering the loop, the matrix is first reduced to logarithmic base and is vectorized.
     2. A permutation matrix of size(n) is created 
     3. In the loop, The permutation matrix is randomly permuted and its determinant is taken
     4. To compute the current_value- 
         A_step1 is multiplied with permutation matrix : this changes the row order in the matrix
         np.trace is applied to the result : This function is used to sum the diagonal elements
         exponential is taken : Exponential of log_e is taken, this will cancel each other 
         Finally, the current value is added over the iterations.
     5. The resultant current_value is averged over the share of permutations ranged over the max_index iterations
     
 Interpretation of the code: 
     It is understood that the determinant of a circular matrix for a 3*3 matrix is given by $a^3 + b^3 + c^3 - 3abc$
     where matrix A = circulant([a b c])
     And this code is trying to compute the determinant by computing the above formula.
     1. Matrix is reduced to logarithmic base because while performing trace function, the addition of diagonal elements ensures         multiplication of elements in the normal domain.
     2. There are therefore $n!$ permutation matrices of size $n$.
     3. we are iterating 1000number of times.Each permutation matrix is repeated $1000/n!$
     4. If $det(Ap) = 1$ then $trace\_mod = a^3 or\ b^3 or\ c^3$
     5. If $det(Ap) =-1$ then $trace\_mod = a\times b\times c$
According to the code, $trace\_mat = e^{trace(logA\times Ap)} $
    $current\_value \approx 1000/n!(a^3 + b^3 + c^3 - 3\times (a\times b\times c)) $
$a\_step2 \approx current\_value\times n! / 1000 $
$a\_step2 \approx (a^3 + b^3 + c^3 - 3\times (a\times b\times c) = det(A)$
     
     
 
 
 * Is this a property of circulant matrices, or would this finding extend to arbitrary matrices over the real numbers?
  
  Answer : This property is distinctive to circular matrices and hence cannot be extended to any arbitrary matrices

### Tasks
 * Build code to explore the fact that the determinant function is multiplicative: $\mathrm{det}(AB) = \mathrm{det}(A) \mathrm{det}(B)$.

In [60]:
matrixA = np.random.randint(1,5,(4,4))
matrixB = np.random.randint(1,5,(4,4))
matrix_AB = np.dot(matrixA,matrixB)
detA = det(matrixA)
detB = det(matrixB)
detAB = round(detA*detB)
det_AB =round(det(matrix_AB))


np.set_printoptions(suppress= True)
print("Determinant of A :" , detA)
print("Determinant of B :" , detB)
print("Determinant of AB : , det_AB",det_AB)

print("the Determinant function is multiplicative if det(AB) = det(A)*det(B) and is tested to be ",np.allclose(det_AB,detA*detB))

Determinant of A : -14.0
Determinant of B : 6.000000000000003
Determinant of AB : , det_AB -84
the Determinant function is multiplicative if det(AB) = det(A)*det(B) and is tested to be  True
